default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  database: rails_gke_sample_development
  host: db
  username: postgres
  password:

test:
  <<: *default
  database: rails_gke_sample_test
  host: db
  username: postgres
  password:

production:
  <<: *default
  database: rails_gke_sample_production
  host: <%= ENV["RAILS_DB_HOST"] %>
  username: <%= ENV["RAILS_DB_USER"] %>
  password: <%= ENV["RAILS_DB_PASSWORD"] %>
